# Use a lightweight JDK image
FROM openjdk:17-jdk-slim

# Add a volume for logs (optional)
VOLUME /tmp

# Copy the jar file to the container
COPY target/product-service-1.0.0.jar product-service.jar

# Run the jar file
ENTRYPOINT ["java", "-jar", "/product-service.jar"]
